repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.1
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format
- repo: local
  hooks:
    - id: ty-check
      name: ty check
      entry: ty check
      language: python
      types: [python]
      additional_dependencies:
        - duckdb-ext[duckdb-ext-dev]
        - ty